{% set name = "precious" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/houseabsolute/precious/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 163b284fff7b723f9645312d1a45fe7149885fa40269c6ee92866d46a1da177b

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses

test:
  commands:
    - precious --help

about:
  home: https://github.com/houseabsolute/precious
  license: Apache-2.0 or MIT
  license_file: 
    - LICENSE-APACHE
    - LICENSE-MIT
    - THIRDPARTY.yml
  summary: One code quality tool to rule them all
  dev_url: https://github.com/houseabsolute/precious

extra:
  recipe-maintainers:
    - brycekbargar
