{% set name = "precious" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/houseabsolute/precious/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 55719618f111911cc9ff00bed5c7b080bdffabeb4233faf8812e83c4d08ee6da

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses

test:
  commands:
    - precious --help

about:
  home: https://github.com/houseabsolute/precious
  license: Apache-2.0 or MIT
  license_file:
    - LICENSE-APACHE
    - LICENSE-MIT
    - THIRDPARTY.yml
  summary: One code quality tool to rule them all
  dev_url: https://github.com/houseabsolute/precious

extra:
  recipe-maintainers:
    - brycekbargar
